# Request
sensor_msgs/Image image
string text_prompt
---
# Response
# Segmentation of the region(s) matching the text prompt. Typically mono8 or rgba.
sensor_msgs/Image segmented_image

# 2D detections with class hypotheses and scores
vision_msgs/Detection2DArray detections